---
namespace: prod-k8sbot

replicas: 2

image:
  tag: "1.0"

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 64Mi

#env:
#- name: PORT
#  value: "5000"
#- name: SLACK_VERIFICATION_TOKEN
#  value: 9S7eT2PBGhn2e5ZkPmczulna
#- name: SLACK_CLIENT_ID
#  value: "3115514008.521006508998"
#- name: SLACK_CLIENT_SECRET
#  value: 54d511573da80a8f2fe701247f3311cf
#- name: MONGO_DB_CONNECTION_URL
#  value: mongodb://dev-mk:e5MGchMlitpthZvH@dev-mk-api-shard-00-00-5dciz.gcp.mongodb.net:27017,dev-mk-api-shard-00-01-5dciz.gcp.mongodb.net:27017,dev-mk-api-shard-00-02-5dciz.gcp.mongodb.net:27017/test?ssl=true&replicaSet=dev-mk-api-shard-0&authSource=admin&retryWrites=true
#- name: MONGO_DB_NAME
#  value: test
#- name: MONGO_COLLECTION
#  value: slack

# env:
# - name: GOOGLE_CLOUD_PROJECT
#   value: k8sbot
# - name: GOOGLE_APPLICATION_CREDENTIALS
#   value: /var/run/secret/cloud.google.com/service-account.json
# - name: SLACK_VERIFICATION_TOKEN
#   value: 9S7eT2PBGhn2e5ZkPmczulna
# - name: MONGO_DB_CONNECTION_URL
#   value: mongodb://dev-mk:e5MGchMlitpthZvH@dev-mk-api-shard-00-00-5dciz.gcp.mongodb.net:27017,dev-mk-api-shard-00-01-5dciz.gcp.mongodb.net:27017,dev-mk-api-shard-00-02-5dciz.gcp.mongodb.net:27017/prod-k8sbot?ssl=true&replicaSet=dev-mk-api-shard-0&authSource=admin&retryWrites=true
# - name: MONGO_DB_NAME
#   value: prod-k8sbot
# - name: MONGO_COLLECTION
#   value: slack

ingress:
  annotations:
    kubernetes.io/ingress.class: kong-prod-k8sbot
    certmanager.k8s.io/cluster-issuer: kong-prod
    certmanager.k8s.io/acme-http01-edit-in-place: "true"
    configuration.konghq.com: gcp-install-ingress-cert-manager
  host: gcp-console.managedkube.com
  tls:
    - secretName: gcp-install-tls
      hosts:
        - gcp-console.managedkube.com
