apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "unit.name" . }}
  name: {{ template "unit.name" . }}
  namespace: {{ .Values.namespace }}
spec:
{{- with .Values.servicePorts }}
  ports:
{{ toYaml . | indent 2 }}
{{- end }}

  selector:
    app: {{ template "unit.name" . }}
  sessionAffinity: None
  type: ClusterIP
